# Anypoint Platform APIからの取得データの出力設定
# 各設定項目について：
# - enabled: データの出力要否 (true/false)
# - description: 設定の説明
# - filename: 出力ファイル名

applications:
  enabled: true
  description: APIマネージャーから取得したアプリケーション一覧情報の出力設定
  filename: applications-full.json  # 出力ファイル名
